Add error

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32,6 +32,8 @@ if [ $(echo "$OSTYPE" | grep "darwin") ]; then
     echo "PKG_LIBS= -L$PKGDIR/lib -lgit2 -lssl -lcrypto" >> src/Makevars
     exit 0
   fi
+  echo "Homebrew of libgit2 failed :(";
+  exit 1;
 fi
 
 echo "File git2.h not found. Please install libgit2, e.g: libgit2-devel (rpm) or libgit2-dev (deb)"
